# Generated by Django 2.0 on 2019-07-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_courseorg_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(default='', upload_to='Org/%Y/%m', verbose_name='logo'),
        ),
    ]
